INSERT INTO inventory (name, stock) VALUES ('Philos Pura', 1);
INSERT INTO inventory (name, stock) VALUES ('Khamrah', 1);
INSERT INTO inventory (name, stock) VALUES ('Khamrah Qahwa', 1);
INSERT INTO inventory (name, stock) VALUES ('Fakhar Gold', 1);
INSERT INTO inventory (name, stock) VALUES ('Mandarin Sky', 1);
INSERT INTO inventory (name, stock) VALUES ('Yara', 1);
INSERT INTO inventory (name, stock) VALUES ('Yara Candy', 1);
INSERT INTO inventory (name, stock) VALUES ('Salvo Intense', 1);
INSERT INTO inventory (name, stock) VALUES ('9 PM Rebel', 1);
INSERT INTO inventory (name, stock) VALUES ('9 AM Dive', 1);
INSERT INTO inventory (name, stock) VALUES ('Hayaati Black', 1);
INSERT INTO inventory (name, stock) VALUES ('Hawas Fire', 1);
INSERT INTO inventory (name, stock) VALUES ('Fakhar Black', 1);
INSERT INTO inventory (name, stock) VALUES ('Haya Pink', 1);
INSERT INTO inventory (name, stock) VALUES ('Art of Universe', 1);
INSERT INTO inventory (name, stock) VALUES ('Tropical Vibe', 1);
INSERT INTO inventory (name, stock) VALUES ('Eclaire Pistache', 1);
INSERT INTO inventory (name, stock) VALUES ('Opulent Musk', 1);
INSERT INTO inventory (name, stock) VALUES ('Fakhar Rose', 1);
INSERT INTO inventory (name, stock) VALUES ('Zakat World Cup', -1);