UPDATE inventory SET stock = -1 WHERE name IN (
    'Khamrah',
    'Khamrah Qahwa',
    'Fakhar Gold',
    'Yara',
    'Yara Candy',
    'Salvo Intense',
    '9 PM Rebel',
    '9 AM Dive',
    'Hayaati Black',
    'Hawas Fire',
    'Fakhar Black',
    'Art of Universe',
    'Tropical Vibe',
    'Eclaire Pistache',
    'Opulent Musk',
    'Fakhar Rose',
    'Zakat World Cup',
    'Armaf Odyssey Homme White Edition'
);
